
MODEL_CONFIG:
  IMG_SIZE: 256

TRAINING_CONFIG:

  EPOCH: 100
  BATCH_SIZE: 8

  # lr and lambda
  G_LR : 10e-4
  D_LR : 20e-4
  LAMBDA_TR  : 12.0
  LAMBDA_G_FAKE  : 1
  LAMBDA_G_RECON : 30
  LAMBDA_G_SYTLE : 50
  LAMBDA_G_PERCEP : 0.01
  LAMBDA_D_FAKE  : 1
  LAMBDA_D_REAL  : 1
  LAMBDA_GP : 20000

  # Data augmentation
  AUGMENT : 'tps' # or 'tps, elastic

  #Triplet loss
  TRIPLE_LOSS : 'False' # 'True' or 'False'
  GAN_LOSS : 'lsgan'

  # Optimizer
  OPTIM : ADAM
  BETA1: 0.5
  BETA2: 0.999
  D_CRITIC : 1
  G_CRITIC : 1

  # Settings
  NUM_WORKER : 4
  MODE : 'train'
  CPU_SEED : 123
  GPU_SEED : 456
  USE_TENSORBOARD : 'False' # 'True' or 'False'

  # noise parameter
  DIST : 'uniform' # of 'gaussian'
  A : -1
  B : 1
  MEAN : 0
  STD : 0.01
  #spectral norm
  G_SPEC : 'False'
  D_SPEC : 'True'

  # Directory
  IMG_DIR : 'data'
  TRAIN_DIR : 'colorization_gan4'
  LOG_DIR : 'logs'
  SAMPLE_DIR : 'samples'
  RESULT_DIR : 'results'
  MODEL_DIR : 'models'

  # GPU
  GPU: 1

  # Step Size

  SAMPLE_STEP : 1 # epoch based
  LOG_STEP : 100 # iteration based
  SAVE_STEP : 5 # epoch based
  SAVE_START : 10
  LR_DECAY_STEP : 20

TEST_CONFIG:
  TEST_EPOCH : 100


